name: "Trivy security scanning for containers"
description: "Scans the present IaC files (Dockerfile) for vulnerabilities and builds the image and scans it as well. The results of the scan are pushed to Github's Security tab, if no vulnerabilities are found, the image is pushed to the repo."
inputs:
  image-name:
    description: "The name of the image as it will appear in the remote registry"
    required: true
  image-version:
    description: "The version of the image"
    required: true
  registry:
    description: "The login for the docker registry. e.g: ghcr.io"
    required: true
  registry-username:
    description: "The username for the registry"
    required: true
  registry-password:
    description: "The password for the registry"
    required: true
  severity:
    description: "The minimum severities separated by comma, e.g: CRITICAL, HIGH"
    required: false
    default: "CRITICAL"
runs:
  using: "composite"
  steps:
    - name: Trivy scan on Dockerfile
      uses: aquasecurity/trivy-action@master
      id: scanDocker
      with:
        scan-type: "config"
        hide-progress: false
        format: "sarif"
        exit-code: "1"
        ignore-unfixed: true
        output: "trivy-results-1.sarif"
        severity: "${{ inputs.severity }}"

    - name: Upload Trivy scan results for Dockerfile to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      if: ${{ always() && steps.scanDocker.outcome == 'failure' }}
      with:
        sarif_file: "trivy-results-1.sarif"

    - name: Build the image and login
      shell: bash
      run: |
        docker build . --tag "${{ inputs.image-name }}:${{ inputs.image-version }}"
        docker login "${{ inputs.registry }}" -u "${{ inputs.registry-username }}" -p "${{ inputs.registry-password }}"

    - name: Trivy scan on image
      uses: aquasecurity/trivy-action@master
      id: scanImage
      with:
        image-ref: "${{ inputs.image-name }}:${{ inputs.image-version }}"
        format: "sarif"
        output: "trivy-results-2.sarif"
        exit-code: "1"
        severity: "${{ inputs.severity }}"
      env:
        TRIVY_USERNAME: ${{ inputs.registry-username }}
        TRIVY_PASSWORD: ${{ inputs.registry-password }}

    - name: Upload Trivy scan results for image to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      if: ${{ always() && steps.scanImage.outcome == 'failure' }}
      with:
        sarif_file: "trivy-results-2.sarif"

    - name: Push the image to the registry
      shell: bash
      run: |
        echo "Pushing to registry: ${{ inputs.image-name }}:${{ inputs.image-version }}"
        docker push "${{ inputs.image-name }}:${{ inputs.image-version }}"
